import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import { Header } from '@/components/Header/Header'
import { Footer } from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RH Consultoria',
  description: 'Generated by Edilan Ribeiro',
  icons: {
    icon: {
      type: 'image/png',
      url: '/favicon.png',
    },
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='w-vw flex flex-col justify-center overflow-clip'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
